### ISSUE TITLE
installation problem on Centos

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [JoaoRodrigues/interfacea#9]
I have a cluster and have to install Python library "interfacea" on Centos Linux. I installed some required libraries but not "simtk.openmm". I didn't try instructions on simtk.org, because it is for Ubuntu and too long to do. How can I solve the problem easily?

```
[root@loginnode interfacea]# python3
Python 3.6.8 (default, Apr 25 2019, 21:02:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import interfacea
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/interfacea/interfacea/__init__.py", line 24, in <module>
    import simtk.openmm.app as app
ModuleNotFoundError: No module named 'simtk.openmm'
```

**Comment by JoaoRodrigues** [comment]
Hi @alirizaaribas-ibg 

If you are a user wanting to install it for yourself, use the method describd in the README: install Miniconda3 on your home directory and then use the `environment.yml` to install all the dependencies.

If you want to install the library for all users in a cluster, my suggestion is to install Miniconda somewhere where all users can access it and then follow the same procedure as above. Then make sure to give proper instructions to your users to allow them to activate the right environment. Otherwise, without environments, you will have to install OpenMM yourself.

Does this help?

**Comment by alirizaaribas-ibg** [comment]
Hi @JoaoRodrigues,
I installed "interfacea" environment for users. Now it is running well. I send information to users about usage of environment.
Best regards.

**Comment by JoaoRodrigues** [comment]
Great, thanks. Let me know if you have more questions.

**Comment by alirizaaribas-ibg** [comment]
Nowadays, I have a problem while installing. I tried to install `kdtrees` but failed. How can I overcome this problem? Please help me.

> (interfacea) [root@loginnode interfacea]# python -m interfacea
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/interfacea/lib/python3.7/runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/opt/anaconda3/envs/interfacea/lib/python3.7/runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/opt/anaconda3/envs/interfacea/lib/python3.7/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/root/interfacea/interfacea/__init__.py", line 25, in <module>
>     from .io import read, fetch  # noqa: F401
>   File "/root/interfacea/interfacea/io/__init__.py", line 29, in <module>
>     from .aabuilder import AllAtomStructureBuilder
>   File "/root/interfacea/interfacea/io/aabuilder.py", line 32, in <module>
>     from interfacea.core.structure import Structure
>   File "/root/interfacea/interfacea/core/structure.py", line 36, in <module>
>     from interfacea.spatial import kdtrees
> ImportError: cannot import name 'kdtrees' from 'interfacea.spatial' (unknown location)

I followed the instructions from github:

> git clone https://github.com/joaorodrigues/interfacea.git interfacea
> cd interfacea
> conda create --yes --quiet --name interfacea python=3.7
> conda env update --name interfacea --file environment.yml
> python setup.py build
> python setup.py install
> conda activate interfacea
> 
> Quick Example(s)
> python -m interfacea

**Comment by JoaoRodrigues** [comment]
Hi @alirizaaribas-ibg please use the 'master' branch for installations, not the latest `refactor` branch. The link is here: https://github.com/JoaoRodrigues/interfacea/tree/master
